### ISSUE TITLE
Realm instance throwing error after a certain time

### ISSUE THREAD

**Issue by eagskunst** [horizontalsystems/bitcoin-kit-android#249]
In the demo app, the realm instance throws an error and makes the app crash after a certain time (5 minutes approx.). This is the error being thrown:

```
E/AndroidRuntime: FATAL EXCEPTION: pool-4-thread-1
    Process: io.horizontalsystems.bitcoinkit.demo, PID: 11555
    java.lang.IllegalStateException: This Realm instance has already been closed, making it unusable.
        at io.realm.internal.OsResults$Iterator.<init>(OsResults.java:52)
        at io.realm.OrderedRealmCollectionImpl$RealmCollectionIterator.<init>(OrderedRealmCollectionImpl.java:558)
        at io.realm.OrderedRealmCollectionImpl.iterator(OrderedRealmCollectionImpl.java:239)
        at io.realm.RealmResults.iterator(RealmResults.java:72)
        at io.horizontalsystems.bitcoinkit.transactions.TransactionSyncer.getPendingTransactions(TransactionSyncer.kt:71)
        at io.horizontalsystems.bitcoinkit.network.peer.PeerGroup.handlePendingTransactions(PeerGroup.kt:278)
        at io.horizontalsystems.bitcoinkit.network.peer.PeerGroup.access$handlePendingTransactions(PeerGroup.kt:18)
        at io.horizontalsystems.bitcoinkit.network.peer.PeerGroup$assignNextSyncPeer$1.run(PeerGroup.kt:229)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:761)
```

**Comment by rafaelekol** [comment]
Currently there is ongoing refactoring, we are replacing Realm database with Room database.
