### ISSUE TITLE
Failed to synchronize in android 6.0.1

### ISSUE THREAD

**Issue by leonardojpr** [horizontalsystems/bitcoin-kit-android#252]
Hi, there's an error in Android 6.0.1 in the demo app.
This is the error thrown by the console:

`03-18 15:08:15.413 15882-16320/io.horizontalsystems.bitcoinkit.demo E/AndroidRuntime: FATAL EXCEPTION: pool-3-thread-1
    Process: io.horizontalsystems.bitcoinkit.demo, PID: 15882
    java.lang.StackOverflowError: stack size 1038KB
        at io.realm.internal.NativeObjectReference$ReferencePool.add(NativeObjectReference.java:38)
        at io.realm.internal.NativeObjectReference.<init>(NativeObjectReference.java:79)
        at io.realm.internal.NativeContext.addReference(NativeContext.java:41)
        at io.realm.internal.UncheckedRow.<init>(UncheckedRow.java:46)
        at io.realm.internal.UncheckedRow.getByRowIndex(UncheckedRow.java:78)
        at io.realm.internal.Table.getUncheckedRow(Table.java:418)
        at io.realm.BaseRealm.get(BaseRealm.java:626)
        at io.realm.io_horizontalsystems_bitcoinkit_models_BlockRealmProxy.realmGet$header(io_horizontalsystems_bitcoinkit_models_BlockRealmProxy.java:157)
        at io.realm.io_horizontalsystems_bitcoinkit_models_BlockRealmProxy.createDetachedCopy(io_horizontalsystems_bitcoinkit_models_BlockRealmProxy.java:798)
        at io.realm.io_horizontalsystems_bitcoinkit_models_BlockRealmProxy.createDetachedCopy(io_horizontalsystems_bitcoinkit_models_BlockRealmProxy.java:802)`

**Comment by abdrasulov** [comment]
Hello @leonardojpr. We will work on this issue soon. Please use the production branch.
