### ISSUE TITLE
On calling kit refresh, peergroup is started second time, which causes exception.

### ISSUE THREAD

**Issue by omurovch** [horizontalsystems/bitcoin-kit-android#315]
java.lang.IllegalThreadStateException
        at java.lang.Thread.start(Thread.java:724)
        at io.horizontalsystems.bitcoincore.managers.SyncManager.onSyncingFinished(SyncManager.kt:44)
        at io.horizontalsystems.bitcoincore.managers.InitialSyncer.sync(InitialSyncer.kt:31)
        at io.horizontalsystems.bitcoincore.managers.SyncManager.start(SyncManager.kt:19)
        at io.horizontalsystems.bitcoincore.BitcoinCore.start(BitcoinCore.kt:328)
        at io.horizontalsystems.bitcoincore.BitcoinCore.refresh(BitcoinCore.kt:342)
        at io.horizontalsystems.bitcoincore.AbstractKit.refresh(AbstractKit.kt:36)
        at io.horizontalsystems.bankwallet.core.BitcoinBaseAdapter.refresh(BitcoinBaseAdapter.kt:75)
        at io.horizontalsystems.bankwallet.core.managers.AdapterManager$refreshAdapters$1.run(AdapterManager.kt:44)

**Comment by tmedetbekov** [comment]
Fixed in #316
