### ISSUE TITLE
Crashing while sending transaction request

### ISSUE THREAD

**Issue by mahmoudHijaziN** [horizontalsystems/bitcoin-kit-android#554]
Hey I am receiving the following crash while trying to send a transaction request:

```
com.example.cryptobitcoinkit E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.cryptobitcoinkit, PID: 5600
    java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:523)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1055)
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1055) 
     Caused by: io.horizontalsystems.bitcoincore.network.peer.PeerGroup$Error: peers not synced
        at io.horizontalsystems.bitcoincore.transactions.TransactionSender.canSendTransaction(TransactionSender.kt:44)
        at io.horizontalsystems.bitcoincore.transactions.TransactionCreator.create(TransactionCreator.kt:31)
        at io.horizontalsystems.bitcoincore.transactions.TransactionCreator.create(TransactionCreator.kt:18)
        at io.horizontalsystems.bitcoincore.BitcoinCore.send(BitcoinCore.kt:457)
        at io.horizontalsystems.bitcoincore.AbstractKit.send(AbstractKit.kt:60)
        at io.horizontalsystems.bitcoincore.AbstractKit.send$default(AbstractKit.kt:59)
        at com.example.cryptobitcoinkit.MainActivity.onCreate$lambda-0(MainActivity.kt:86)
        at com.example.cryptobitcoinkit.MainActivity.$r8$lambda$OxZgY3xITDn8ztSYdEnEMoew3NM(Unknown Source:0)
        at com.example.cryptobitcoinkit.MainActivity$$ExternalSyntheticLambda0.onClick(Unknown Source:2)
        at android.view.View.performClick(View.java:7281)
        at com.google.android.material.button.MaterialButton.performClick(MaterialButton.java:1119)
        at android.view.View.performClickInternal(View.java:7255)
        at android.view.View.access$3600(View.java:828)
        at android.view.View$PerformClick.run(View.java:27925)
        at android.os.Handler.handleCallback(Handler.java:900)
        at android.os.Handler.dispatchMessage(Handler.java:103)
        at android.os.Looper.loop(Looper.java:219)
        at android.app.ActivityThread.main(ActivityThread.java:8393)
```

However, the setup is done correctly and i am receiving the wallet object correctly like the following:
`status => {Synced Until=Fri Oct 15 16:40:12 GMT+03:00 2021, Syncing Peer=N/A, Derivation=BIP44, Sync State=Syncing-0.0, Last Block Height=2099200}, balance => BalanceInfo(spendable=157223820, unspendable=0), receiveAddress => mg2Lbzhw7CKeGzaWWioPnDXRtLAXnwkVqK`

I am waiting until the sync is done and pressing a button to send a request.
I am testing on test-net syncmode and as you can notice the syncing peer is N/A

**Comment by muzeitlimited** [comment]
This is the logs after sync

`bitcoinKit synced, status => {Synced Until=Fri Oct 15 17:20:42 GMT+03:00 2021, Syncing Peer=N/A, Derivation=BIP44, Sync State=Synced, Last Block Height=2099202, Peer 1={Status=Synced, Host=160.16.233.215, Best Block=2099202, tasks=no tasks}}, balance => BalanceInfo(spendable=157233820, unspendable=0), receiveAddress => mjGCQzLPUWofybohco9mZXTxEfxz6a4z16`

**Comment by muzeitlimited** [comment]
Hey @abdrasulov, how can i fix this issue? to force a peer connection or any other way?

**Comment by abdrasulov** [comment]
@muzeitlimited the kit should handle itself. I could not reproduce it. It successfully keeps connections with 10 peers. Can you please check the same using the default demo app?

**Comment by muzeitlimited** [comment]
Hey @abdrasulov, will test it on the Main Net later, since now I am testing sending/receiving transactions through bitcoin test faucets. I tested the testNet on a different network ( a faster one) and the sync was a bit faster so you're probably right.
