### ISSUE TITLE
SQL Lite exception 

### ISSUE THREAD

**Issue by Serpivskyi** [horizontalsystems/bitcoin-kit-android#557]
Sometimes, after I trying to run wallet, I get this exception
android.database.sqlite.SQLiteException: no such table: BlockHash (code 1 SQLITE_ERROR): , while compiling: SELECT * FROM BlockHash ORDER BY sequence ASC, height ASC LIMIT ?
        at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
        at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:986)
        at android.database.sqlite.SQLiteConnection.executeForCursorWindow(SQLiteConnection.java:935)
        at android.database.sqlite.SQLiteSession.executeForCursorWindow(SQLiteSession.java:838)
        at android.database.sqlite.SQLiteQuery.fillWindow(SQLiteQuery.java:62)
        at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:155)
        at android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:142)
        at io.horizontalsystems.bitcoincore.storage.BlockHashDao_Impl.getBlockHashesSortedSequenceHeight(BlockHashDao_Impl.java:222)
        at io.horizontalsystems.bitcoincore.storage.Storage.getBlockHashesSortedBySequenceAndHeight(Storage.kt:42)
        at io.horizontalsystems.bitcoincore.blocks.BlockSyncer.getBlockHashes(BlockSyncer.kt:68)
        at io.horizontalsystems.bitcoincore.blocks.InitialBlockDownload.downloadBlockchain(InitialBlockDownload.kt:152)
        at io.horizontalsystems.bitcoincore.blocks.InitialBlockDownload.access$downloadBlockchain(InitialBlockDownload.kt:15)
        at io.horizontalsystems.bitcoincore.blocks.InitialBlockDownload$assignNextSyncPeer$1.run

**Comment by rafaelekol** [comment]
Can write steps, how to reproduce this exception.
